Anedotas/Models/Anedota.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Anedotas.Models
{
    public class AnedotaModel
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Contexto { get; set; }
        public string ContextoResposta { get; set; }
        public string Autor { get; set; }


        public AnedotaModel()
        {
            Id = 0;
            Autor = "Anónimo";
            Titulo = "Sem titulo";
            Contexto = string.Empty;
            ContextoResposta = string.Empty;
        }
    }
}

Anedotas/Models/ErrorViewModel.cs
namespace Anedotas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Anedotas/Controllers/AnedotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Anedotas.Data;
using Anedotas.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace Anedotas.Controllers
{
    public class AnedotaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnedotaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Anedota
        public async Task<IActionResult> Index()
        {
              return _context.AnedotaModel != null ? 
                          View(await _context.AnedotaModel.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.AnedotaModel'  is null.");
        }

        public async Task<IActionResult> SearchForm(string titulo)
        {
            return _context.AnedotaModel != null ?
                        View() :
                        Problem("Entity set 'ApplicationDbContext.AnedotaModel'  is null.");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SearchAnedota(string titulo)
        {
            return _context.AnedotaModel != null ?
                        View("Index",await _context.AnedotaModel.Where(x => x.Titulo.Contains(titulo)).ToListAsync() ?? null) :
                        Problem("Entity set 'ApplicationDbContext.AnedotaModel'  is null.");
        }

        // GET: Anedota/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AnedotaModel == null)
            {
                return NotFound();
            }

            var anedotaModel = await _context.AnedotaModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (anedotaModel == null)
            {
                return NotFound();
            }

            return View(anedotaModel);
        }

        // GET: Anedota/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Anedota/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Contexto,ContextoResposta,Autor")] AnedotaModel anedotaModel)
        {
            if (ModelState.IsValid)
            {
                var autor = User.FindFirstValue(ClaimTypes.NameIdentifier);
                anedotaModel.Autor = autor;
                _context.Add(anedotaModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(anedotaModel);
        }



        // GET: Anedota/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AnedotaModel == null)
            {
                return NotFound();
            }

            var anedotaModel = await _context.AnedotaModel.FindAsync(id);
            if (anedotaModel == null)
            {
                return NotFound();
            }
            return View(anedotaModel);
        }

        // POST: Anedota/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Contexto,ContextoResposta")] AnedotaModel anedotaModel)
        {
            if (id != anedotaModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(anedotaModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnedotaModelExists(anedotaModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(anedotaModel);
        }

        // GET: Anedota/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AnedotaModel == null)
            {
                return NotFound();
            }

            var anedotaModel = await _context.AnedotaModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (anedotaModel == null)
            {
                return NotFound();
            }

            return View(anedotaModel);
        }

        // POST: Anedota/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AnedotaModel == null)
            {
                return Problem("Entity set 'ApplicationDbContext.AnedotaModel'  is null.");
            }
            var anedotaModel = await _context.AnedotaModel.FindAsync(id);
            if (anedotaModel != null)
            {
                _context.AnedotaModel.Remove(anedotaModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnedotaModelExists(int id)
        {
          return (_context.AnedotaModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Anedotas/Controllers/HomeController.cs
using Anedotas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Anedotas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Anedotas/Views/Anedota/Create.cshtml
@model Anedotas.Models.AnedotaModel

@{
    ViewData["Title"] = "Create";
}

<h1>Criar Anedota</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contexto" class="control-label"></label>
                <input asp-for="Contexto" class="form-control" />
                <span asp-validation-for="Contexto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContextoResposta" class="control-label"></label>
                <input asp-for="ContextoResposta" class="form-control" />
                <span asp-validation-for="ContextoResposta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Anedotas/Views/Anedota/Delete.cshtml
@model Anedotas.Models.AnedotaModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Tem a certeza que deseja apagar esta anedota?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contexto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contexto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContextoResposta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContextoResposta)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar à Lista</a>
    </form>
</div>

Anedotas/Views/Anedota/Details.cshtml
@model Anedotas.Models.AnedotaModel

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contexto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contexto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContextoResposta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContextoResposta)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Voltar à lista</a>
</div>

Anedotas/Views/Anedota/Edit.cshtml
@model Anedotas.Models.AnedotaModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contexto" class="control-label"></label>
                <input asp-for="Contexto" class="form-control" />
                <span asp-validation-for="Contexto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContextoResposta" class="control-label"></label>
                <input asp-for="ContextoResposta" class="form-control" />
                <span asp-validation-for="ContextoResposta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Anedotas/Views/Anedota/Index.cshtml
@model IEnumerable<Anedotas.Models.AnedotaModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Criar Novo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>

Anedotas/Views/Anedota/SearchForm.cshtml
@model Anedotas.Models.AnedotaModel

<h4>AnedotaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SearchAnedota">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Pesquisar Anedotas</label>
                <input name="Titulo" class="form-control" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Anedotas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo</h1>
    <p>Aqui poderás encontrar anedotas hilariantes criadas pelos próprio utilizadores.</p>
    <p>Tens alguma anedota? Compartilha conosco a partir de anedotas e criar anedota</p>
    <img src="images/dentures-fail.gif" width="300"/>
</div>

Anedotas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Anedotas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Anedotas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Anedotas</a> *@
                <img src="~/images/logo.png" width="40"/>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anedota" asp-action="Index">Anedotas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anedota" asp-action="SearchForm">Pesquisa</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Anedotas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>